In [2]:
import torch

# Create a 2D tensor
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

# Display the original tensor
print("Original Tensor:")
print(tensor)

# Sum along all dimensions (default behavior)
sum_default = tensor.sum()
print("\nSum (Default):", sum_default)

# Sum along a specific dimension (e.g., dim=0 for rows)
sum_dim0 = tensor.sum(dim=0)
print("\nSum along dimension 0 (rows):")
print(sum_dim0)
print(sum_dim0.shape)

# Sum along the other dimension (e.g., dim=1 for columns)
sum_dim1 = tensor.sum(dim=1)
print("\nSum along dimension 1 (columns):")
print(sum_dim1)
print(sum_dim1.shape)

# Sum along a specific dimension (e.g., dim=0 for rows)
sum_dim0 = tensor.sum(dim=0, keepdim=True)
print("\nSum along dimension 0, keepdim True (rows):")
print(sum_dim0)
print(sum_dim0.shape)

# Sum along the other dimension (e.g., dim=1 for columns)
sum_dim1 = tensor.sum(dim=1, keepdim=True)
print("\nSum along dimension 1 (columns):")
print(sum_dim1)
print(sum_dim1.shape)


Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Sum (Default): tensor(45)

Sum along dimension 0 (rows):
tensor([12, 15, 18])
torch.Size([3])

Sum along dimension 1 (columns):
tensor([ 6, 15, 24])
torch.Size([3])

Sum along dimension 0, keepdim True (rows):
tensor([[12, 15, 18]])
torch.Size([1, 3])

Sum along dimension 1 (columns):
tensor([[ 6],
        [15],
        [24]])
torch.Size([3, 1])


In [6]:
import torch

tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

# Display the original tensor
print("Original Tensor:")
print(tensor)
print(tensor.shape)

# Sum along dimension 0 without keepdim
sum_dim0_no_keepdim = tensor.sum(dim=0, keepdim=False)

# Sum along dimension 0 with keepdim
sum_dim0_keepdim = tensor.sum(dim=0, keepdim=True)

print("Sum along dimension 0 without keepdim:")
print(sum_dim0_no_keepdim)

print("\nSum along dimension 0 with keepdim:")
print(sum_dim0_keepdim)


Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
Sum along dimension 0 without keepdim:
tensor([5, 7, 9])

Sum along dimension 0 with keepdim:
tensor([[5, 7, 9]])


In [8]:
# Tensor Tutorial - Tensors

In [9]:
import torch
import numpy as np

In [10]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [11]:
# create tensor from numpy
a = np.array(data)
x_np = torch.from_numpy(a)
x_np, a

(tensor([[1, 2],
         [3, 4]]),
 array([[1, 2],
        [3, 4]]))

In [16]:
# from another tensor - retains properties (shape and datatype) unless overridden
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_ones, x_rand

(tensor([[1, 1],
         [1, 1]]),
 tensor([[0.0940, 0.9136],
         [0.8321, 0.4096]]))

In [18]:
# create tensor based on shape
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
rand_tensor, ones_tensor, zeros_tensor

(tensor([[0.7623, 0.7910, 0.6005],
         [0.4134, 0.1243, 0.5269]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [21]:
# attributes
t = torch.rand(3,4)
t, t.shape, t.dtype, t.device

(tensor([[0.1167, 0.0362, 0.7312, 0.2926],
         [0.4257, 0.1127, 0.2330, 0.3681],
         [0.6747, 0.0258, 0.8133, 0.6229]]),
 torch.Size([3, 4]),
 torch.float32,
 device(type='cpu'))

In [22]:
torch.cuda.is_available()

False

In [25]:
tensor = torch.rand(4,4)
tensor, tensor[0], tensor[:,0], tensor[...,-1],tensor[:,-1]

(tensor([[0.2429, 0.6281, 0.6582, 0.4493],
         [0.8681, 0.2256, 0.2734, 0.4572],
         [0.5981, 0.3929, 0.3289, 0.0309],
         [0.1563, 0.9387, 0.3520, 0.5596]]),
 tensor([0.2429, 0.6281, 0.6582, 0.4493]),
 tensor([0.2429, 0.8681, 0.5981, 0.1563]),
 tensor([0.4493, 0.4572, 0.0309, 0.5596]),
 tensor([0.4493, 0.4572, 0.0309, 0.5596]))

In [26]:
tensor[:,2] = 1
tensor

tensor([[0.2429, 0.6281, 1.0000, 0.4493],
        [0.8681, 0.2256, 1.0000, 0.4572],
        [0.5981, 0.3929, 1.0000, 0.0309],
        [0.1563, 0.9387, 1.0000, 0.5596]])

In [30]:
# concat tensor together on 0, or 1 dim:
t1 = torch.cat([tensor,tensor],dim=1)
t2 = torch.cat([tensor, tensor], dim=0)
t1,t2

(tensor([[0.2429, 0.6281, 1.0000, 0.4493, 0.2429, 0.6281, 1.0000, 0.4493],
         [0.8681, 0.2256, 1.0000, 0.4572, 0.8681, 0.2256, 1.0000, 0.4572],
         [0.5981, 0.3929, 1.0000, 0.0309, 0.5981, 0.3929, 1.0000, 0.0309],
         [0.1563, 0.9387, 1.0000, 0.5596, 0.1563, 0.9387, 1.0000, 0.5596]]),
 tensor([[0.2429, 0.6281, 1.0000, 0.4493],
         [0.8681, 0.2256, 1.0000, 0.4572],
         [0.5981, 0.3929, 1.0000, 0.0309],
         [0.1563, 0.9387, 1.0000, 0.5596],
         [0.2429, 0.6281, 1.0000, 0.4493],
         [0.8681, 0.2256, 1.0000, 0.4572],
         [0.5981, 0.3929, 1.0000, 0.0309],
         [0.1563, 0.9387, 1.0000, 0.5596]]))

In [44]:
# arithmetic ops - matrix multiplication
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
x = torch.rand_like(tensor)
torch.mul(tensor, tensor, out = x)
x

tensor([[5.9004e-02, 3.9446e-01, 1.0000e+00, 2.0190e-01],
        [7.5363e-01, 5.0877e-02, 1.0000e+00, 2.0906e-01],
        [3.5770e-01, 1.5437e-01, 1.0000e+00, 9.5288e-04],
        [2.4445e-02, 8.8123e-01, 1.0000e+00, 3.1310e-01]])

In [49]:
# single-element tensors
agg = tensor.sum()
agg, agg.item(), type(agg.item())

(tensor(9.5477), 9.547708511352539, float)

In [53]:
# inplace ops are denoted with _ suffix 
t = torch.rand(4,4)
print(t)
print(t.add_(1))

tensor([[0.6028, 0.6183, 0.6238, 0.5735],
        [0.4881, 0.5419, 0.9079, 0.6192],
        [0.8587, 0.1784, 0.9256, 0.9913],
        [0.5183, 0.8278, 0.7790, 0.6513]])
tensor([[1.6028, 1.6183, 1.6238, 1.5735],
        [1.4881, 1.5419, 1.9079, 1.6192],
        [1.8587, 1.1784, 1.9256, 1.9913],
        [1.5183, 1.8278, 1.7790, 1.6513]])


In [57]:
# bridge with numpy - sharing underlying memory
t= torch.ones(5)
n = t.numpy()
t.add_(1)
t, n

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

In [61]:
# bridge - numpy to tensor
n = np.ones(5)
t = torch.from_numpy(n)
print(t)
np.add(n,1, out=n)
print(t)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [12]:
# concat tensors together on rows(0) and on cols(1)
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])
a, torch.cat((a,b),0), torch.cat((a,b),1)

(tensor([[1, 2],
         [3, 4]]),
 tensor([[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]),
 tensor([[1, 2, 5, 6],
         [3, 4, 7, 8]]))

In [19]:
# manipulating a flat array,which uses the underlying storage, it's really efficient
a = torch.arange(18)
a.view(3,6), a.view(2,9), a.view(3,3,2), a.storage()

(tensor([[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16, 17]]),
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
         [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 tensor([[[ 0,  1],
          [ 2,  3],
          [ 4,  5]],
 
         [[ 6,  7],
          [ 8,  9],
          [10, 11]],
 
         [[12, 13],
          [14, 15],
          [16, 17]]]),
  0
  1
  2
  3
  4
  5
  6
  7
  8
  9
  10
  11
  12
  13
  14
  15
  16
  17
 [torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 18])

In [22]:
# strides
t= torch.tensor([[1,2],[3,4]])
t.stride(), t.storage()

((2, 1),
  1
  2
  3
  4
 [torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 4])

In [26]:
t[1,0], t[1,:]

(tensor(3), tensor([3, 4]))